const ATSTruckTemplateImages = [
    //Trucks
    { name: '[Western Star 57X] Cabin A (72-inch Sleeper)', url: '/assets/templates/trucks/[Western Star 57X] Cabin A (72-inch Sleeper).png' },
    { name: '[Western Star 57X] Cabin B (Day Cab)', url: '/assets/templates/trucks/[Western Star 57X] Cabin B (Day Cab).png' },
    { name: '[Western Star 57X] Unreleased Cabin (48-inch Sleeper).png', url: '/assets/templates/trucks/[Western Star 57X] Unreleased Cabin (48-inch Sleeper).png' },
    { name: '[Western Star 5700XE] Cabin C (Day Cab)', url: '/assets/templates/trucks/[Western Star 5700XE] Cabin C (Day Cab).png' },
    { name: '[Western Star 5700XE] Cabin A (82-inch Sleeper)', url: '/assets/templates/trucks/[Western Star 5700XE] Cabin A (82-inch Sleeper).png' },
    { name: '[Western Star 49X] Cabin B (48-inch Sleeper)', url: '/assets/templates/trucks/[Western Star 49X] Cabin B (48-inch Sleeper).png' },
    { name: '[Western Star 49X] Cabin C (Day Cab)', url: '/assets/templates/trucks/[Western Star 49X] Cabin C (Day Cab).png' },
    { name: '[Western Star 49X] Cabin A (72-inch Sleeper)', url: '/assets/templates/trucks/[Western Star 49X] Cabin A (72-inch Sleeper).png' },
    { name: '[[Volvo VNL 2014] Cabin C (300, alt uvset)', url: '/assets/templates/trucks/[Volvo VNL 2014] Cabin C (300, alt uvset).png' },
    { name: '[Volvo VNL 2014] Cabin A (780, alt uvset)', url: '/assets/templates/trucks/[Volvo VNL 2014] Cabin A (780, alt uvset).png' },
    { name: '[Volvo VNL 2014] Cabin B (730, alt uvset)', url: '/assets/templates/trucks/[Volvo VNL 2014] Cabin B (730, alt uvset).png' },
    { name: '[Volvo VNL] Cabin C (300)', url: '/assets/templates/trucks/[Volvo VNL] Cabin C (300).png' },
    { name: '[Volvo VNL] Cabin A (860)', url: '/assets/templates/trucks/[Volvo VNL] Cabin A (860).png' },
    { name: '[Volvo VNL] Cabin B (740)', url: '/assets/templates/trucks/[Volvo VNL] Cabin B (740).png' },
    { name: '[Peterbilt 579] Cabin C (Duty Cabin, alt uvset)', url: '/assets/templates/trucks/[Peterbilt 579] Cabin C (Duty Cabin, alt uvset).png' },
    { name: '[Peterbilt 579] Cabin A (Hi Rise Sleeper, alt uvset)', url: '/assets/templates/trucks/[Peterbilt 579] Cabin A (Hi Rise Sleeper, alt uvset).png' },
    { name: '[Peterbilt 579] Cabin B (Stand Up Sleeper, alt uvset)', url: '/assets/templates/trucks/[Peterbilt 579] Cabin B (Stand Up Sleeper, alt uvset).png' },
    { name: '[Peterbilt 389] Cabin C (Day Cab, alt uvset)', url: '/assets/templates/trucks/[Peterbilt 389] Cabin C (Day Cab, alt uvset).png' },
    { name: '[Peterbilt 389] Cabin A (Ultra Cab Sleeper, alt uvset)', url: '/assets/templates/trucks/[Peterbilt 389] Cabin A (Ultra Cab Sleeper, alt uvset).png' },
    { name: '[Peterbilt 389] Cabin B (Low Roof Sleeper, alt uvset)', url: '/assets/templates/trucks/[Peterbilt 389] Cabin B (Low Roof Sleeper, alt uvset).png' },
    { name: '[Mack Anthem] Cabin A (70-inch Sleeper, alt uvset)', url: '/assets/templates/trucks/[Mack Anthem] Cabin A (70-inch Sleeper, alt uvset).png' },
    { name: '[Mack Anthem] Cabin B (48-inch Sleeper, alt uvset)', url: '/assets/templates/trucks/[Mack Anthem] Cabin B (48-inch Sleeper, alt uvset).png' },
    { name: '[Mack Anthem] Cabin C (Day Cab, alt uvset)', url: '/assets/templates/trucks/[Mack Anthem] Cabin C (Day Cab, alt uvset).png' },
    { name: '[Kenworth W900] Cabin C (Day Cab)', url: '/assets/templates/trucks/[Kenworth W900] Cabin C (Day Cab).png' },
    { name: '[Kenworth W900] Cabin A (86-inch Sleeper)', url: '/assets/templates/trucks/[Kenworth W900] Cabin A (86-inch Sleeper).png' },
    { name: '[Kenworth W900] Cabin B (72-inch Sleeper)', url: '/assets/templates/trucks/[Kenworth W900] Cabin B (72-inch Sleeper).png' },
    { name: '[Kenworth T680] Cabin B (Mid Roof Sleeper, alt uvset)', url: '/assets/templates/trucks/[Kenworth T680] Cabin B (Mid Roof Sleeper, alt uvset).png' },
    { name: '[Kenworth T680] Cabin C (Duty Day Cabin, alt uvset)', url: '/assets/templates/trucks/[Kenworth T680] Cabin C (Duty Day Cabin, alt uvset).png' },
    { name: '[Kenworth T680] Cabin A (Hi Rise Sleeper, alt uvset)', url: '/assets/templates/trucks/[Kenworth T680] Cabin A (Hi Rise Sleeper, alt uvset).png' },
    { name: '[International LT] Cabin C (Day Cab)', url: '/assets/templates/trucks/[International LT] Cabin C (Day Cab).png' },
    { name: '[International LT] Cabin A (Skyrise Sleeper)', url: '/assets/templates/trucks/[Kenworth T680] Cabin A (Hi Rise Sleeper, alt uvset).png' },
    { name: '[International LT] Cabin B (Hi-Rise Sleeper)', url: '/assets/templates/trucks/[International LT] Cabin B (Hi-Rise Sleeper).png' },
    { name: '[International LoneStar] Cabin B (High Rise Sleeper)', url: '/assets/templates/trucks/[International LoneStar] Cabin B (High Rise Sleeper).png' },
    { name: '[International LoneStar] Cabin C (Day Cab)', url: '/assets/templates/trucks/[International LoneStar] Cabin C (Day Cab).png' },
    { name: '[International LoneStar] Cabin A (Sky Rise Sleeper)', url: '/assets/templates/trucks/[International LoneStar] Cabin A (Sky Rise Sleeper).png' },
    { name: '[International 9900i] Cabin C (Day Cab)', url: '/assets/templates/trucks/[International 9900i] Cabin C (Day Cab).png' },
    { name: '[International 9900i] Cabin A (72-inch Sleeper)', url: '/assets/templates/trucks/[International 9900i] Cabin A (72-inch Sleeper).png' },
    { name: '[International 9900i] Cabin B (51-inch Sleeper)', url: '/assets/templates/trucks/[International 9900i] Cabin B (51-inch Sleeper).png' },
    { name: '[Freightliner Cascadia] Cabin D (Day Cab)', url: '/assets/templates/trucks/[Freightliner Cascadia] Cabin D (Day Cab).png' },
    { name: '[Freightliner Cascadia] Cabin A (72-inch Sleeper RR)', url: '/assets/templates/trucks/[Freightliner Cascadia] Cabin A (72-inch Sleeper RR).png' },
    { name: '[Freightliner Cascadia] Cabin B (72-inch Sleeper XT)', url: '/assets/templates/trucks/[Freightliner Cascadia] Cabin B (72-inch Sleeper XT).png' },
    { name: '[Freightliner Cascadia] Cabin C (48-inch Sleeper)', url: '/assets/templates/trucks/[Freightliner Cascadia] Cabin C (48-inch Sleeper).png' },
  ];

const ATSTrailerTemplateImages = [
  // Trailers
  { name: '[SCS Grain Hopper] Trailer Rear', url: '/assets/templates/trailers/[SCS Grain Hopper] Trailer Rear.png' },
  { name: '[SCS Grain Hopper] Body (28 feet)', url: '/assets/templates/trailers/[SCS Grain Hopper] Body (28 feet).png' },
  { name: '[SCS Grain Hopper] Body (40 feet)', url: '/assets/templates/trailers/[SCS Grain Hopper] Body (40 feet).png' },
  { name: '[SCS Grain Hopper] Body (50 feet)', url: '/assets/templates/trailers/[SCS Grain Hopper] Body (50 feet).png' },
  { name: '[SCS Gas Tank] Body (32 ft)', url: '/assets/templates/trailers/[SCS Gas Tank] Body (32 ft).png' },
  { name: '[SCS Gas Tank] Body (43 ft)', url: '/assets/templates/trailers/[SCS Gas Tank] Body (43 ft).png' },
  { name: '[SCS Gas Tank] Body (48 ft)', url: '/assets/templates/trailers/[SCS Gas Tank] Body (48 ft).png' },
  { name: '[SCS Gas Tank] Body (53 ft)', url: '/assets/templates/trailers/[SCS Gas Tank] Body (53 ft).png' },
  { name: '[SCS Fuel Tank] Body (53 ft)', url: '/assets/templates/trailers/[SCS Fuel Tank] Body (53 ft).png' },
  { name: '[SCS Fuel Tank] Body (28 ft)', url: '/assets/templates/trailers/[SCS Fuel Tank] Body (28 ft).png' },
  { name: '[SCS Fuel Tank] Body (32 ft)', url: '/assets/templates/trailers/[SCS Fuel Tank] Body (32 ft).png' },
  { name: '[SCS Fuel Tank] Body (43 ft)', url: '/assets/templates/trailers/[SCS Fuel Tank] Body (43 ft).png' },
  { name: '[SCS Food Tank] Chassis (Dolly)', url: '/assets/templates/trailers/[SCS Food Tank] Chassis (Dolly).png' },
  { name: '[SCS Food Tank] Body (48 feet)', url: '/assets/templates/trailers/[SCS Food Tank] Body (48 feet).png' },
  { name: '[SCS Food Tank] Body (53 feet)', url: '/assets/templates/trailers/[SCS Food Tank] Body (53 feet).png' },
  { name: '[SCS Food Tank] Body (28 feet)', url: '/assets/templates/trailers/[SCS Food Tank] Body (28 feet).png' },
  { name: '[SCS Food Tank] Body (28 feet, Double)', url: '/assets/templates/trailers/[SCS Food Tank] Body (28 feet, Double).png' },
  { name: '[SCS Food Tank] Body (43 feet)', url: '/assets/templates/trailers/[SCS Food Tank] Body (43 feet).png' },
  { name: '[SCS Flatbed] Sliding Tarp (53 feet)', url: '/assets/templates/trailers/[SCS Flatbed] Sliding Tarp (53 feet).png' },
  { name: '[SCS Flatbed] Sliding Tarp (28 feet)', url: '/assets/templates/trailers/[SCS Flatbed] Sliding Tarp (28 feet).png' },
  { name: '[SCS Flatbed] Sliding Tarp (32 feet)', url: '/assets/templates/trailers/[SCS Flatbed] Sliding Tarp (32 feet).png' },
  { name: '[SCS Flatbed] Sliding Tarp (45 feet)', url: '/assets/templates/trailers/[SCS Flatbed] Sliding Tarp (45 feet).png' },
  { name: '[SCS Flatbed] Sliding Tarp (48 feet)', url: '/assets/templates/trailers/[SCS Flatbed] Sliding Tarp (48 feet).png' },
  { name: '[SCS Dumper] Body - Side Dumper (36 ft)', url: '/assets/templates/trailers/[SCS Dumper] Body - Side Dumper (36 ft).png' },
  { name: '[SCS Dumper] Body - End Dumper (30 ft)', url: '/assets/templates/trailers/[SCS Dumper] Body - End Dumper (30 ft).png' },
  { name: '[SCS Dumper] Body - End Dumper (36 ft)', url: '/assets/templates/trailers/[SCS Dumper] Body - End Dumper (36 ft).png' },
  { name: '[SCS Dumper] Body - Side Dumper (30 ft)', url: '/assets/templates/trailers/[SCS Dumper] Body - Side Dumper (30 ft).png' },
  { name: '[SCS Dry Bulk] Body (32 ft)', url: '/assets/templates/trailers/[SCS Dry Bulk] Body (32 ft).png' },
  { name: '[SCS Dry Bulk] Body (42 ft)', url: '/assets/templates/trailers/[SCS Dry Bulk] Body (42 ft).png' },
  { name: '[SCS Dry Bulk] Body (48 ft)', url: '/assets/templates/trailers/[SCS Dry Bulk] Body (48 ft).png' },
  { name: '[SCS Dry Bulk] Body (22 ft)', url: '/assets/templates/trailers/[SCS Dry Bulk] Body (22 ft).png' },
  { name: '[SCS Drop Deck] Sliding Tarp (48 ft)', url: '/assets/templates/trailers/[SCS Drop Deck] Sliding Tarp (48 ft).png' },
  { name: '[SCS Drop Deck] Sliding Tarp (53 ft)', url: '/assets/templates/trailers/[SCS Drop Deck] Sliding Tarp (53 ft).png' },
  { name: '[SCS Chip Van] Body (Chip Van)', url: '/assets/templates/trailers/[SCS Chip Van] Body (Chip Van).png' },
  { name: '[SCS Chip Van] Body (Chip Van, Moving Floor)', url: '/assets/templates/trailers/[SCS Chip Van] Body (Chip Van, Moving Floor).png' },
  { name: '[SCS Chip Van] Trailer Front', url: '/assets/templates/trailers/[SCS Chip Van] Trailer Front.png' },
  { name: '[SCS Chip Van] Trailer Rear', url: '/assets/templates/trailers/[SCS Chip Van] Trailer Rear.png' },
  { name: '[SCS Chip Van] Body (Belly Van)', url: '/assets/templates/trailers/[SCS Chip Van] Body (Belly Van).png' },
  { name: '[SCS Bulk Feed] Body', url: '/assets/templates/trailers/[SCS Bulk Feed] Body.png' },
  { name: '[Lode King Prestige] Body (Single)', url: '/assets/templates/trailers/[Lode King Prestige] Body (Single).png' },
  { name: '[Lode King Prestige] Body (B-Double)', url: '/assets/templates/trailers/[Lode King Prestige] Body (B-Double).png' },
]

export {ATSTruckTemplateImages, ATSTrailerTemplateImages}